/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Adrian
 */
import GUI.Login;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        BtProducts = new javax.swing.JButton();
        BtStocks = new javax.swing.JButton();
        BtCustomers = new javax.swing.JButton();
        BtSuppliers = new javax.swing.JButton();
        BtSales = new javax.swing.JButton();
        BtOrder = new javax.swing.JButton();
        BtUsers = new javax.swing.JButton();
        BtUserLog = new javax.swing.JButton();
        BtLogout = new javax.swing.JButton();
        labDash = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(46, 196, 182));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        navPanel.setBackground(new java.awt.Color(255, 255, 255));

        BtProducts.setBackground(new java.awt.Color(255, 191, 105));
        BtProducts.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtProducts.setText("PRODUCTS");
        BtProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtProductsActionPerformed(evt);
            }
        });

        BtStocks.setBackground(new java.awt.Color(255, 191, 105));
        BtStocks.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtStocks.setText("CURRENT STOCKS");
        BtStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtStocksActionPerformed(evt);
            }
        });

        BtCustomers.setBackground(new java.awt.Color(255, 191, 105));
        BtCustomers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtCustomers.setText("CUSTOMERS");
        BtCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCustomersActionPerformed(evt);
            }
        });

        BtSuppliers.setBackground(new java.awt.Color(255, 191, 105));
        BtSuppliers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtSuppliers.setText("SUPPLIERS");
        BtSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSuppliersActionPerformed(evt);
            }
        });

        BtSales.setBackground(new java.awt.Color(255, 191, 105));
        BtSales.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtSales.setText("SALES");
        BtSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalesActionPerformed(evt);
            }
        });

        BtOrder.setBackground(new java.awt.Color(255, 191, 105));
        BtOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtOrder.setText("ORDER");
        BtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtOrderActionPerformed(evt);
            }
        });

        BtUsers.setBackground(new java.awt.Color(255, 191, 105));
        BtUsers.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtUsers.setText("USERS");
        BtUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUsersActionPerformed(evt);
            }
        });

        BtUserLog.setBackground(new java.awt.Color(255, 191, 105));
        BtUserLog.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtUserLog.setText("USER LOG");
        BtUserLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUserLogActionPerformed(evt);
            }
        });

        BtLogout.setBackground(new java.awt.Color(255, 159, 28));
        BtLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtLogout.setText("LOGOUT");
        BtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLogoutActionPerformed(evt);
            }
        });

        labDash.setBackground(new java.awt.Color(255, 255, 255));
        labDash.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labDash.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dash.png"))); // NOI18N
        labDash.setText("Dashboard");

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labDash)
                            .addGroup(navPanelLayout.createSequentialGroup()
                                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtSales, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labDash)
                .addGap(88, 88, 88)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSales, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtUserLog, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(BtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        displayPanel.setBackground(new java.awt.Color(203, 243, 240));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtProductsActionPerformed
        // TODO add your handling code here:
        Products products = new Products();
        
        // Set the dashboard panel to the displayPanel in the main JFrame
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.setContentPane(products);
        mainFrame.revalidate();
        mainFrame.repaint();

    }//GEN-LAST:event_BtProductsActionPerformed

    private void BtStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtStocksActionPerformed
        // TODO add your handling code here:
       Stocks stock = new Stocks();
        
       JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.setContentPane(stock);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_BtStocksActionPerformed

    private void BtCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCustomersActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BtCustomersActionPerformed

    private void BtSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSuppliersActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtSuppliersActionPerformed

    private void BtSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtSalesActionPerformed

    private void BtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtOrderActionPerformed

    private void BtUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUsersActionPerformed
        // TODO add your handling code here:
        
        Users user = new Users();
        
       JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.setContentPane(user);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_BtUsersActionPerformed

    private void BtUserLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUserLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtUserLogActionPerformed

    private void BtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLogoutActionPerformed
        // TODO add your handling code here:
         Login loginScreen = new Login();
        
        // Set the Login JFrame visible
        loginScreen.setVisible(true);
    }//GEN-LAST:event_BtLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCustomers;
    private javax.swing.JButton BtLogout;
    private javax.swing.JButton BtOrder;
    private javax.swing.JButton BtProducts;
    private javax.swing.JButton BtSales;
    private javax.swing.JButton BtStocks;
    private javax.swing.JButton BtSuppliers;
    private javax.swing.JButton BtUserLog;
    private javax.swing.JButton BtUsers;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel labDash;
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables
}
